spring.application.name=tingeso-back
spring.datasource.url = ${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://167.172.246.45/auth/realms/Tingeso
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/Tingeso/protocol/openid-connect/certs