test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Run Tests with Coverage
        run: mvn test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Log Coverage Percentage
        run: |
          echo "Coverage total: ${{ steps.jacoco.outputs.coverage }}"
          echo "Branch Coverage total: ${{ steps.jacoco.outputs.branches }}"

      - name: Add Coverage to Summary
        run: |
          echo "Reporte de Cobertura" >> $GITHUB_STEP_SUMMARY
          echo "Instrucciones: ${{ steps.jacoco.outputs.coverage-percentage }}%" >> $GITHUB_STEP_SUMMARY
          echo "Ramas (Branches): ${{ steps.jacoco.outputs.branches-percentage }}%" >> $GITHUB_STEP_SUMMARY